### ISSUE TITLE
Run bitbake mc:qemuamd64-focal:isar-image-base, but can't generate wic image

### ISSUE THREAD

**Issue by xiayishusheng** [ilbers/isar#80]
when is build `bitbake mc:qemuamd64-focal:isar-image-base`, it has error, cannot generate wic image ~, i have not find a way to resolve this.

```
$ bitbake mc:qemuamd64-focal:isar-image-base
Parsing recipes: 100% |##################################################################################################################################################| Time: 0:00:06
Parsing of 38 .bb files complete (0 cached, 38 parsed). 1254 targets, 0 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |################################################################################################| Time: 0:00:17Sstate summary: Wanted 0 Local 0 Network 0 Missed 0 Current 4 (0% match, 100% complete)
NOTE: Executing Tasks
ERROR: mc:qemuamd64-focal:isar-image-base-1.0-r0 do_wic_image: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_wic_image(d)
     0003:
File: '/data/yocto/isar2/meta/classes/wic-img.bbclass', lineno: 150, function: do_wic_image
     0146:    progress_reporter = bb.progress.MultiStageProgressReporter(d, weights)
     0147:
     0148:    for cmd in cmds:
     0149:        progress_reporter.next_stage()
 *** 0150:        bb.build.exec_func(cmd, d)
     0151:    progress_reporter.finish()
     0152:}
     0153:addtask wic_image before do_image after do_image_tools
     0154:
File: '/data/yocto/isar2/bitbake/lib/bb/build.py', lineno: 251, function: exec_func
     0247:    with bb.utils.fileslocked(lockfiles):
     0248:        if ispython:
     0249:            exec_func_python(func, d, runfile, cwd=adir)
     0250:        else:
 *** 0251:            exec_func_shell(func, d, runfile, cwd=adir)
     0252:
     0253:    try:
     0254:        curcwd = os.getcwd()
     0255:    except:
File: '/data/yocto/isar2/bitbake/lib/bb/build.py', lineno: 452, function: exec_func_shell
     0448:    with open(fifopath, 'r+b', buffering=0) as fifo:
     0449:        try:
     0450:            bb.debug(2, "Executing shell function %s" % func)
     0451:            with open(os.devnull, 'r+') as stdin, logfile:
 *** 0452:                bb.process.run(cmd, shell=False, stdin=stdin, log=logfile, extrafiles=[(fifo,readfifo)])
     0453:        finally:
     0454:            os.unlink(fifopath)
     0455:
     0456:    bb.debug(2, "Shell function %s finished" % func)
File: '/data/yocto/isar2/bitbake/lib/bb/process.py', lineno: 182, function: run
     0178:        if not stderr is None:
     0179:            stderr = stderr.decode("utf-8")
     0180:
     0181:    if pipe.returncode != 0:
 *** 0182:        raise ExecutionError(cmd, pipe.returncode, stdout, stderr)
     0183:    return stdout, stderr
Exception: bb.process.ExecutionError: Execution of '/data/yocto/isar2/build/tmp/work/ubuntu-focal-amd64/isar-image-base-qemuamd64-wic-img/1.0-r0/temp/run.generate_wic_image.2568489' failed with exit code 1:
INFO: Creating image(s)...

Traceback (most recent call last):
  File "/data/yocto/isar2/scripts/wic", line 542, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/data/yocto/isar2/scripts/wic", line 537, in main
    return hlp.invoke_subcommand(args, parser, hlp.wic_help_usage, subcommands)
  File "/data/yocto/isar2/scripts/lib/wic/help.py", line 83, in invoke_subcommand
    subcmd[0](args, usage)
  File "/data/yocto/isar2/scripts/wic", line 219, in wic_create_subcommand
    engine.wic_create(wks_file, rootfs_dir, bootimg_dir, kernel_dir,
  File "/data/yocto/isar2/scripts/lib/wic/engine.py", line 190, in wic_create
    plugin.do_create()
  File "/data/yocto/isar2/scripts/lib/wic/plugins/imager/direct.py", line 97, in do_create
    self.create()
  File "/data/yocto/isar2/scripts/lib/wic/plugins/imager/direct.py", line 181, in create
    self._image.prepare(self)
  File "/data/yocto/isar2/scripts/lib/wic/plugins/imager/direct.py", line 356, in prepare
    part.prepare(imager, imager.workdir, imager.oe_builddir,
  File "/data/yocto/isar2/scripts/lib/wic/partition.py", line 176, in prepare
    plugin.do_configure_partition(self, srcparams_dict, creator,
  File "/data/yocto/isar2/meta/scripts/lib/wic/plugins/source/bootimg-efi-isar.py", line 219, in do_configure_partition
    cls.do_configure_systemdboot(hdddir, creator, cr_workdir, source_params)
  File "/data/yocto/isar2/meta/scripts/lib/wic/plugins/source/bootimg-efi-isar.py", line 177, in do_configure_systemdboot
    kernel, initrd = isar_get_filenames(get_bitbake_var("IMAGE_ROOTFS"))
  File "/data/yocto/isar2/meta/scripts/lib/wic/plugins/source/../isarpluginbase.py", line 37, in isar_get_filenames
    raise WicError("initrd %s not found" % (os.path.join(rootfs_dir, "boot", initrd)))
NameError: name 'WicError' is not defined
WARNING: exit code 1 from a shell command.


ERROR: Logfile of failure stored in: /data/yocto/isar2/build/tmp/work/ubuntu-focal-amd64/isar-image-base-qemuamd64-wic-img/1.0-r0/temp/log.do_wic_image.2568489
ERROR: Task (mc:qemuamd64-focal:/data/yocto/isar2/meta-isar/recipes-core/images/isar-image-base.bb:do_wic_image) failed with exit code '1'
NOTE: Tasks Summary: Attempted 42 tasks of which 41 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  mc:qemuamd64-focal:/data/yocto/isar2/meta-isar/recipes-core/images/isar-image-base.bb:do_wic_image
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by jan-kiszka** [comment]
Works fine here for latest 'next', at least when using the kas-isar container as build env. You will likely have to describe your build env in more details.

**Comment by xiayishusheng** [comment]
> Works fine here for latest 'next', at least when using the kas-isar container as build env. You will likely have to describe your build env in more details.

Thanks，use 'next' branch is ok~😃
